name: CI
on: [push]
jobs:
  build:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: tru—É
    - name: Run
      env:
        SECRETS_URL: ${{ secrets.DISCORD }}
      run: bundle exec fastlane custom_build_and_test
